### ISSUE TITLE
Having trouble with Plex detecting Telly

### ISSUE THREAD

**Issue by MentulTH** [tombowditch/telly#102] opened 2018-05-31 03:05 UTC
Was able to get Telly manually running via Windows power shell. Now, when trying to add to plex (running telly on windows machine and plex on shield), plex cannot find telly. After clicking "Add Live TV/DVR", I've tried both localhost:6077 and the Windows machine's IP:6077, neither worked. Any insight is appreciated.

**Comment by HazCod** [comment] 2018-05-31 10:48
Windows firewall perhaps?

**Comment by HazCod** [comment] 2018-05-31 10:48
Did you set ‘-listen=0.0.0.0:6077’ by the way?

**Comment by MentulTH** [comment] 2018-05-31 12:38
Not sure. Any ideas on editing firewall allow? Do I need to use -listen statement with machine running telly ip ( like -listen 0.0.0.0:6077)?

**Comment by MentulTH** [comment] 2018-05-31 12:39
Because right now when telly is running in the power shell, it says listening localhost:6077 (running on windows machine) and plex cant find it. Have tried both on same windows machine and on browser on nvidia shield (where plex server is running).

**Comment by HazCod** [comment] 2018-05-31 13:16
Well, it says exactly what the problem is. `localhost` means only the Windows machine can reach it.
If you use `-listen <ip-of-windows-pc>:6077` it will listen on an external interface, allowing others to reach it.

**Comment by HazCod** [comment] 2018-06-13 12:01
Closing since no feedback.

**Closed by HazCod** 2018-06-13 12:01 UTC
